encyclopedia/urls.py
from django.urls import path

from . import views


app_name="encyclopedia"
urlpatterns = [
    path("", views.index, name="index"),
    path("wiki/<str:entry>", views.entry, name="entry"),
    path("search", views.search, name="search"),
    path("create", views.create, name="create"),
    path("wiki/<str:entry>/edit", views.edit, name="edit"),
    path("wiki/<str:entry>/submit", views.submitEntry, name="submitEntry"),
    path("wiki/", views.random, name="random")
]

wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls"))
]

encyclopedia/models.py
from django.db import models

# Create your models here.

encyclopedia/views.py
from django.shortcuts import render
from random import choice
from markdown2 import Markdown
from . import util
from django import forms
from django.urls import reverse
from django.http import HttpResponseRedirect, HttpResponse
import secrets

#adding a class to create a form text input instead of manually setting input field
class SearchForm(forms.Form):
    #adding an input field that will be called in every function for search
    query = forms.CharField(label="",
        widget=forms.TextInput(attrs={'placeholder':'Search Wiki'}))

#adding a class for the create page option to help us input new title and content
class AddNewPage(forms.Form):
    title = forms.CharField(label="", widget=forms.TextInput(attrs={'placeholder': 'Enter title', 'id': 'new-entry-title'}))
    content = forms.CharField(label= "", widget=forms.Textarea(attrs={'size': 50, 'placeholder': 'Enter your content', 'id': 'new-entry-content', 'style': 'display:flex; width:80%; height:40%; margin-top:15px;' }))
#adding a class  
class EditPageFields(forms.Form):
    title = forms.CharField(label="", widget=forms.TextInput(attrs={'id': 'edit-entry-title'}))
    content = forms.CharField(label="", widget=forms.Textarea(attrs={'id': 'edit-entry-content','style':'display:flex; width:80%; height:40%; margin-top:15px;'}))
#function for the index page
def index(request):
    return render(request, "encyclopedia/index.html", {
        "entries": util.list_entries(),
        "form": SearchForm()
    })

#view to show a specific page the user search in url
def entry(request, entry):
    markdowner=Markdown()
    #get the data the user typed in the url
    entrypage= util.get_entry(entry)
    #if it is non existent redirect to error page html
    if entrypage is None:
        return render(request, "encyclopedia/nonExistingEntry.html", {
            "title": entry,
            "form":SearchForm()
        })
        # if it is existent redirect the user to the  entry page
    else:
        return render(request,"encyclopedia/entry.html", {
            "entry": markdowner.convert(entrypage),
            "title":entry,
            "form": SearchForm()
        })

# fuction for the search bar
def search(request):
    if request.method == 'POST':
        entries_found= []
        #Get the data entered in the field
        form = SearchForm(request.POST)
        if form.is_valid():
            #getting the Data entered in the search bar
            dataentred = form.cleaned_data["query"]
            #all entries
            entries = util.list_entries()
            for entry in entries:
                #if the data was found
                if dataentred.lower() == entry.lower():
                    title = entry
                    entry = util.get_entry(title)
                    #redirect the user to the entry page
                    return HttpResponseRedirect(reverse("encyclopedia:entry", args=[title]))
                #if the letters entered are part of the letters in the entry add it to the empty list we created above
                if dataentred.lower() in entry.lower():
                    entries_found.append(entry)
                
               #default
            return render(request, "encyclopedia/index.html", {
            "entries2": entries_found,
            "search":True,
            "value":dataentred,
            "form": SearchForm()
            
        })

#function for creating entry        
def create(request):
    if request.method == 'POST':
        #get the data from AddNewPage entered and store it in variable
        newentry = AddNewPage(request.POST)

        if newentry.is_valid():
            #extracting the title and content separately and storing them in variables
            title = newentry.cleaned_data['title']
            content = newentry.cleaned_data['content']
            # list of available entries
            available_entries = util.list_entries()
            for entry in available_entries:
                # if the user tries to create an already existing entry display an error message
                if entry.lower() == title.lower():
                    return render(request, "encyclopedia/createnew.html",{
                        "form": SearchForm(),
                        "addNewPage": AddNewPage(),
                        "errormessage": "The wiki page you are trying to create already exists..."
                    })
            #adding mark down to entered data the "n" part is to break the title from the body in different lines
            newentrytitle = '#' + title
            newentrybody = "\n" + content

            all_entered_content = newentrytitle + newentrybody
            #saving the entered data in the entries file and by calling save_entry from util
            util.save_entry(title, all_entered_content)
            entry = util.get_entry(title)
            return render(request, "encyclopedia/entry.html",{
                "entryTitle" : newentrytitle,
                "entry": newentrybody,
                "form":SearchForm()
            })
    #default
    return render(request, "encyclopedia/createnew.html", {
        "form": SearchForm(),
        "addNewPage": AddNewPage()
    } )

def edit(request, entry):
    
    if request.method == "POST":
        # Get data for the entry so it can be edited
        entrypage = util.get_entry(entry)

        editpage = EditPageFields(initial={'title': entry, 'content': entrypage})

        return render(request, "encyclopedia/edit.html", {
            "form": SearchForm(),
            "editEntry": editpage,
            "entry": entrypage,
            "title": entry
        })
    
def submitEntry(request, entry):
    if request.method == 'POST':
        markdowner=Markdown()
        #get the edited entered data
        edited_post = EditPageFields(request.POST)
        if edited_post.is_valid():
            #get the newely edited values both the title and content
            edited_title = edited_post.cleaned_data['title']
            edited_content = edited_post.cleaned_data['content']
            
            # if the changed title is not the same as before
            if edited_title != entry:
                #using f string to find the entry and if found store it in a variable
                filename = f"entries/{entry}.md"
                #Find it then delete it
                if default_storage.exist(filename):
                    default_storage.delete(filename)

            #save the newley entered edited entries
            util.save_entry(edited_title, edited_content)
            edited_entry = util.get_entry(edited_title)   
          #after it has been saved and edited display it in the entries       
        return render(request, "encyclopedia/entry.html",{
                "title":edited_title,
                "entry": markdowner.convert(edited_entry),
                "form":SearchForm(),            
                "msg_success": "Wiki Page was Successfully updated"
                })           
    
 #The random function
def random(request):
    #get all the entries 
    entries = util.list_entries()
    # randomly select an entry using secrets 
    title = secrets.choice(entries)
    # get the normal entry
    entry = util.get_entry(title)
    #redirect to the entry page
    return HttpResponseRedirect(reverse("encyclopedia:entry", args=[title]))

                
 

        

encyclopedia/templates/encyclopedia/createnew.html
{% extends "encyclopedia/layout.html" %}


{%  block title %}
   Wiki
{% endblock %}

{% block body %}
<h1>Create A New Wiki Page</h1>
{% if errormessage %}
    <p style="color: red">{{ errormessage }}</p>
{% endif %}
<form action="{% url 'encyclopedia:create' %}" method="POST">
    {% csrf_token %}
    {{ addNewPage }}
    <br/>
    <input type="submit">
</form>
{% endblock %}

encyclopedia/templates/encyclopedia/edit.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Wiki
{% endblock %}

{% block body %}
    <h1>Edit Entry</h1>
    <form action="{% url 'encyclopedia:submitEntry' title %}" method="POST">
        {{ editEntry }}
        {% csrf_token %}
        <br>
        <button type="submit">Submit Edit</button>
    </form>
{% endblock %}

encyclopedia/templates/encyclopedia/entry.html
{% extends "encyclopedia/layout.html" %}

{% block title%}
    {{title}}
{% endblock%}

{% block body %}
    {% if msg_success %}
        <p style="color: green;">{{ msg_success }}</p>
    {% endif %}
    {{entry|safe}}
    <form action ="{% url 'encyclopedia:edit' title %}" method="POST">
        <button>Edit Wiki Page</button>
        {% csrf_token %}
    </form>
{% endblock %}

encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block form %}

{% endblock %}

{% block body %}
    <h1>All Pages</h1>

    <ul>
        
        {% for entry in entries %}
            <li><a href="/wiki/{{entry}}">{{ entry }}</a href={""}></li>
        {% endfor %}

        {% if search == True %}
        <p style="color: rgb(255, 0, 0); text-align: left;">Were you searching for any of these pages?</p>
        {% for entry in entries2 %}
            <li><a href="/wiki/{{entry}}">{{ entries2 }}</a ></li>
        {% endfor %}
        {% endif %}
    </ul>

{% endblock %}

encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
                
                <form action="{% url 'encyclopedia:search' %}" method="POST">
                    {% csrf_token %}
                     {{ form }}    
                </form>
                <div>
                    <a href="{% url 'encyclopedia:index' %}">Home</a>
                </div>
                <div>
                   <a href="{% url 'encyclopedia:create' %}">Create New Page</a> 
                </div>
                <div>
                   <a href="{% url 'encyclopedia:random' %}">Random Page</a>
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>

encyclopedia/templates/encyclopedia/nonExistingEntry.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
 {{entryTitle}}
{% endblock %}

{% block body %}
    <h1>{{entryTitle}}</h1>
    <p>We are sorry the subject you are looking for {{entryTitle}} was not found. You can click on Home to see the available list of pages.</p>
{% endblock %}